version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - restore_cache:
          key: website-cache
      - run:
          name: install deps
          command: yarn
      - run:
          name: tests
          command: |
            echo 'export DEBUG=phenomic:*' >> $BASH_ENV
            yarn test
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - save_cache:
          key: website-cache
          paths:
            - website/.screenshots
            - website/public/showcase/entry
workflows:
  version: 2
  test:
    jobs:
      - test
